version: '3.8'

services:
  springboot:
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_management_system
    # volumes:
    #   - mysql-data:/var/lib/mysql/container

  react:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: react-app
    environment:
      REACT_APP_API_URL: http://springboot:8080

    ports:
      - "3000:80"

# volumes:
#   mysql-data:
