version: '3.8'

services:
  springboot:
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_management_system
    volumes:
      - mysql-data:/var/lib/mysql/container

  react:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"

volumes:
  mysql-data:
